version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "80:80"
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'GdE1234*'
      MYSQL_DATABASE: 'estoque'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'GdE1234*'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
